### ISSUE TITLE
Update hibernate validator to 6.1.5 Final

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/distribution#15]
After doing seedstack/seed#275, update the version in the parent POM of the distribution so generated projects benefit from it.

**Comment by smoneuse** [comment]
Just updating hibernate validator version won't fit.
I have the following Issue :
```
java.lang.NoSuchMethodError: javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
	at
org.hibernate.validator.internal.xml.config.ValidationBootstrapParameters.<init>(ValidationBootstrapParameters.java:65)
```

Need version 8.0 of javaee-web-api
( see https://stackoverflow.com/questions/47947293/maven-using-wrong-version-of-javax-validation/49693042#49693042 )

**Comment by adrienlauer** [comment]
Done in 20.11
